import { Product, Category, BannerSlide, LookbookItem, TrendingTile, LogisticsSettings, DeliveryZone, Coupon, AnnouncementSettings, FooterSettings, HomeSection } from '@/types';
import { doc, setDoc, writeBatch } from 'firebase/firestore';
import { db } from './firebase';

export const INITIAL_ANNOUNCEMENT: AnnouncementSettings = {
  enabled: false,
  text: "BUY LESS, CHOOSE WELL",
};

export const INITIAL_FOOTER_SETTINGS: FooterSettings = {
  brandName: "Dream Fashion",
  brandTagline: "Modern trend-forward fashion platform for Bangladesh. Premium casual shirts, polos, contemporary tailoring, and nationwide doorstep delivery.",
  phone: "+880 1712-345678",
  whatsapp: "+880 1712-345678",
  email: "support@dreamfashion.com.bd",
  address: "House 14, Road 7, Sector 4, Uttara, Dhaka - 1230, Bangladesh",
  workingHours: "Saturday – Thursday: 10:00 AM – 9:00 PM (Friday Closed)",
  facebookUrl: "https://facebook.com/hodako17",
  instagramUrl: "https://instagram.com",
  tiktokUrl: "https://tiktok.com",
  youtubeUrl: "https://youtube.com",
  linkedinUrl: "https://linkedin.com",
  copyrightText: "© 2026 Dream Fashion Bangladesh. All rights reserved.",
  creatorName: "Azizul Hakim Khan",
  creatorUrl: "https://facebook.com/hodako17",
  showPaymentIcons: true,
  newsletterHeadline: "JOIN THE DREAM CLUB",
  newsletterSubtext: "Subscribe to receive exclusive drop alerts, private lookbooks, and 10% off your first online order.",
  quickLinks: [
    { label: "Home", url: "/" },
    { label: "Casual Shirts", url: "/category/casual-shirts" },
    { label: "Polo Shirts", url: "/category/polos" },
    { label: "Men's Collection", url: "/category/men" },
    { label: "Shop All", url: "/shop" },
  ],
  policyLinks: [
    { label: "Track Your Order", url: "/track-order" },
    { label: "Delivery & Shipping", url: "/shipping" },
    { label: "Returns & Exchanges", url: "/returns" },
    { label: "Privacy Policy", url: "/privacy" },
    { label: "Terms of Service", url: "/terms" },
  ],
};


export const INITIAL_CATEGORIES: Category[] = [
  {
    id: "men",
    name: "Men's Collection",
    slug: "men",
    imageUrl: "/images/categories/men.avif",
    order: 1,
  },
  {
    id: "casual-shirts",
    name: "Casual Shirts",
    slug: "casual-shirts",
    imageUrl: "/images/categories/casual-shirts.avif",
    order: 2,
  },
  {
    id: "polos",
    name: "Polo Shirts",
    slug: "polos",
    imageUrl: "/images/categories/polos.avif",
    order: 3,
  },
  {
    id: "women",
    name: "Women's Collection",
    slug: "women",
    imageUrl: "/images/categories/women.avif",
    order: 4,
  },
  {
    id: "dresses",
    name: "Dresses & Gowns",
    slug: "dresses",
    imageUrl: "/images/categories/dresses.avif",
    order: 5,
  },
  {
    id: "outerwear",
    name: "Outerwear & Tailoring",
    slug: "outerwear",
    imageUrl: "/images/categories/outerwear.avif",
    order: 6,
  },
];

export const INITIAL_BANNERS: BannerSlide[] = [
  {
    id: "banner-1",
    imageUrl: "/images/banners/hero_1.avif",
    headline: "SUMMER TAILORING & CASUAL SHIRTS",
    subtext: "Elevated casual shirts and premium polo edits crafted for modern Bangladesh.",
    ctaText: "Shop Collection",
    ctaLink: "/shop",
    order: 1,
    active: true,
  },
  {
    id: "banner-2",
    imageUrl: "/images/banners/hero_2.avif",
    headline: "NEW ARRIVALS: CONTEMPORARY CLASSICS",
    subtext: "Sharp button-downs, textured polos, and fluid silhouettes designed for effortless elegance.",
    ctaText: "Explore New",
    ctaLink: "/shop?sort=newest",
    order: 2,
    active: true,
  },
];

// Rectangular slideable category cards
export const INITIAL_TRENDING_TILES: TrendingTile[] = [
  {
    id: "tile-1",
    title: "SHOP SIGNATURE POLO",
    imageUrl: "/images/tiles/tile-polo.avif",
    link: "/shop?category=polos",
    order: 1,
  },
  {
    id: "tile-2",
    title: "SHOP HALF SLEEVE SHIRTS",
    imageUrl: "/images/tiles/tile-half-sleeve.avif",
    link: "/shop?category=casual-shirts",
    order: 2,
  },
  {
    id: "tile-3",
    title: "SHOP OLD MONEY",
    imageUrl: "/images/tiles/tile-old-money.avif",
    link: "/shop?category=men",
    order: 3,
  },
  {
    id: "tile-4",
    title: "SHOP SHIRT",
    imageUrl: "/images/tiles/tile-shirt.avif",
    link: "/shop?category=casual-shirts",
    order: 4,
  },
];

export const INITIAL_LOOKBOOK: LookbookItem[] = [
  {
    id: "look-1",
    title: "SIGNATURE CASUAL SHIRT",
    subtitle: "Breathable cotton tailoring with modern spread collar",
    imageUrl: "/images/lookbook/look-1.avif",
    link: "/shop?category=casual-shirts",
  },
  {
    id: "look-2",
    title: "TEXTURED KNIT POLO",
    subtitle: "Contrast tipped collar & luxury pique weave",
    imageUrl: "/images/lookbook/look-2.avif",
    link: "/shop?category=polos",
  },
  {
    id: "look-3",
    title: "SATIN DRAPE SILHOUETTE",
    subtitle: "Bias-cut fluid elegance",
    imageUrl: "/images/lookbook/look-3.avif",
    link: "/shop?category=dresses",
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: "df-cs-01",
    title: "Signature Spread Collar Linen Casual Shirt",
    slug: "signature-spread-collar-linen-casual-shirt",
    category: "casual-shirts",
    brand: "Dream Fashion Studio",
    description: "Tailored from pure lightweight French linen, this spread collar shirt offers effortless drape and breathable comfort in warm climates. Features mother-of-pearl buttons and curved hemline suitable for tucked or untucked styling.",
    shortDescription: "Pure French linen spread collar casual shirt with mother-of-pearl buttons.",
    fabricAndCare: "100% Pure Linen. Machine wash cold, gentle cycle. Hang dry in shade.",
    basePrice: 2250,
    salePrice: 1850,
    isNew: true,
    isTrending: true,
    isFeatured: true,
    tags: ["shirt", "casual-shirts", "linen", "men", "new", "trending", "summer"],
    rating: 4.9,
    reviewCount: 28,
    variants: [
      {
        color: "Olive Sage",
        colorHex: "#556B2F",
        size: "M",
        sku: "DF-CS-01-OL-M",
        stock: 15,
        images: ["/images/tiles/tile-shirt.avif", "/images/categories/casual-shirts.avif", "/images/lookbook/look-1.avif"],
      },
      {
        color: "Olive Sage",
        colorHex: "#556B2F",
        size: "L",
        sku: "DF-CS-01-OL-L",
        stock: 20,
        images: ["/images/tiles/tile-shirt.avif", "/images/categories/casual-shirts.avif"],
      },
      {
        color: "Olive Sage",
        colorHex: "#556B2F",
        size: "XL",
        sku: "DF-CS-01-OL-XL",
        stock: 12,
        images: ["/images/tiles/tile-shirt.avif", "/images/categories/casual-shirts.avif"],
      },
      {
        color: "Pure White",
        colorHex: "#FFFFFF",
        size: "M",
        sku: "DF-CS-01-WH-M",
        stock: 18,
        images: ["/images/categories/casual-shirts.avif", "/images/tiles/tile-shirt.avif"],
      },
      {
        color: "Pure White",
        colorHex: "#FFFFFF",
        size: "L",
        sku: "DF-CS-01-WH-L",
        stock: 22,
        images: ["/images/categories/casual-shirts.avif", "/images/tiles/tile-shirt.avif"],
      },
    ],
  },
  {
    id: "df-cs-02",
    title: "Cuban Collar Resort Half Sleeve Shirt",
    slug: "cuban-collar-resort-half-sleeve-shirt",
    category: "casual-shirts",
    brand: "Dream Fashion Studio",
    description: "A breezy relaxed-fit Cuban collar shirt constructed from textured cotton-viscose blend. Perfect for casual weekend outings, beach resorts, or stylish evening layering.",
    shortDescription: "Relaxed fit Cuban camp collar half sleeve shirt in textured weave.",
    fabricAndCare: "65% Cotton, 35% Viscose. Cold machine wash.",
    basePrice: 1950,
    salePrice: 1550,
    isNew: true,
    isTrending: true,
    isFeatured: true,
    tags: ["shirt", "casual-shirts", "half-sleeve", "men", "trending", "summer"],
    rating: 4.8,
    reviewCount: 34,
    variants: [
      {
        color: "Sand Beige",
        colorHex: "#D2B48C",
        size: "M",
        sku: "DF-CS-02-BG-M",
        stock: 20,
        images: ["/images/tiles/tile-half-sleeve.avif", "/images/lookbook/look-1.avif"],
      },
      {
        color: "Sand Beige",
        colorHex: "#D2B48C",
        size: "L",
        sku: "DF-CS-02-BG-L",
        stock: 25,
        images: ["/images/tiles/tile-half-sleeve.avif", "/images/lookbook/look-1.avif"],
      },
      {
        color: "Sand Beige",
        colorHex: "#D2B48C",
        size: "XL",
        sku: "DF-CS-02-BG-XL",
        stock: 14,
        images: ["/images/tiles/tile-half-sleeve.avif", "/images/lookbook/look-1.avif"],
      },
      {
        color: "Midnight Black",
        colorHex: "#111111",
        size: "M",
        sku: "DF-CS-02-BK-M",
        stock: 15,
        images: ["/images/tiles/tile-half-sleeve.avif", "/images/lookbook/look-1.avif"],
      },
    ],
  },
  {
    id: "df-po-01",
    title: "Textured Pique Knit Luxury Polo Shirt",
    slug: "textured-pique-knit-luxury-polo-shirt",
    category: "polos",
    brand: "Dream Fashion Signature",
    description: "Crafted with double-mercerized 100% Egyptian cotton for a subtle sheen and ultra-soft touch. Structured rib collar that won't curl and signature tailored sleeves.",
    shortDescription: "Double-mercerized Egyptian cotton polo shirt with contrast ribbed collar.",
    fabricAndCare: "100% Combed Cotton. Machine wash cold with similar colors.",
    basePrice: 1750,
    salePrice: 1450,
    isNew: true,
    isTrending: true,
    isFeatured: true,
    tags: ["polo", "polos", "men", "trending", "classic"],
    rating: 4.9,
    reviewCount: 42,
    variants: [
      {
        color: "Navy Blue",
        colorHex: "#1B2A47",
        size: "M",
        sku: "DF-PO-01-NV-M",
        stock: 30,
        images: ["/images/tiles/tile-polo.avif", "/images/categories/polos.avif", "/images/lookbook/look-2.avif"],
      },
      {
        color: "Navy Blue",
        colorHex: "#1B2A47",
        size: "L",
        sku: "DF-PO-01-NV-L",
        stock: 25,
        images: ["/images/tiles/tile-polo.avif", "/images/categories/polos.avif"],
      },
      {
        color: "Navy Blue",
        colorHex: "#1B2A47",
        size: "XL",
        sku: "DF-PO-01-NV-XL",
        stock: 15,
        images: ["/images/tiles/tile-polo.avif", "/images/categories/polos.avif"],
      },
      {
        color: "Emerald Green",
        colorHex: "#0D5C3A",
        size: "M",
        sku: "DF-PO-01-GR-M",
        stock: 18,
        images: ["/images/categories/polos.avif", "/images/tiles/tile-polo.avif"],
      },
      {
        color: "Emerald Green",
        colorHex: "#0D5C3A",
        size: "L",
        sku: "DF-PO-01-GR-L",
        stock: 20,
        images: ["/images/categories/polos.avif", "/images/tiles/tile-polo.avif"],
      },
    ],
  },
  {
    id: "df-po-02",
    title: "Contrast Tipped Collar Supima Polo",
    slug: "contrast-tipped-collar-supima-polo",
    category: "polos",
    brand: "Dream Fashion Signature",
    description: "Minimalist Supima cotton polo featuring clean contrast tipping along the collar and cuffs. Tailored slim fit with reinforced 2-button placket.",
    shortDescription: "Supima cotton polo shirt with contrast collar tipping.",
    fabricAndCare: "100% Supima Cotton. Machine wash cold.",
    basePrice: 1850,
    salePrice: 1500,
    isNew: false,
    isTrending: true,
    isFeatured: true,
    tags: ["polo", "polos", "men", "trending"],
    rating: 4.7,
    reviewCount: 19,
    variants: [
      {
        color: "Charcoal Grey",
        colorHex: "#374151",
        size: "M",
        sku: "DF-PO-02-GR-M",
        stock: 20,
        images: ["/images/lookbook/look-2.avif", "/images/tiles/tile-polo.avif"],
      },
      {
        color: "Charcoal Grey",
        colorHex: "#374151",
        size: "L",
        sku: "DF-PO-02-GR-L",
        stock: 24,
        images: ["/images/lookbook/look-2.avif", "/images/tiles/tile-polo.avif"],
      },
      {
        color: "Crisp White",
        colorHex: "#F9FAFB",
        size: "M",
        sku: "DF-PO-02-WH-M",
        stock: 16,
        images: ["/images/tiles/tile-polo.avif", "/images/lookbook/look-2.avif"],
      },
    ],
  },
  {
    id: "df-mn-01",
    title: "Old Money Tailored Pleated Trousers",
    slug: "old-money-tailored-pleated-trousers",
    category: "men",
    brand: "Dream Fashion Tailoring",
    description: "Classic double-pleated sartorial trousers inspired by European vintage tailoring. Features side adjusters, extended waistband, and tapered leg opening.",
    shortDescription: "Double-pleated sartorial trousers with side adjusters.",
    fabricAndCare: "70% Wool-touch Poly, 30% Viscose. Dry clean recommended.",
    basePrice: 2850,
    salePrice: 2350,
    isNew: true,
    isTrending: true,
    isFeatured: true,
    tags: ["men", "pants", "trousers", "old-money", "trending", "tailoring"],
    rating: 4.9,
    reviewCount: 31,
    variants: [
      {
        color: "Warm Khaki",
        colorHex: "#C3B091",
        size: "30",
        sku: "DF-MN-01-KH-30",
        stock: 12,
        images: ["/images/tiles/tile-old-money.avif", "/images/categories/men.avif"],
      },
      {
        color: "Warm Khaki",
        colorHex: "#C3B091",
        size: "32",
        sku: "DF-MN-01-KH-32",
        stock: 18,
        images: ["/images/tiles/tile-old-money.avif", "/images/categories/men.avif"],
      },
      {
        color: "Warm Khaki",
        colorHex: "#C3B091",
        size: "34",
        sku: "DF-MN-01-KH-34",
        stock: 15,
        images: ["/images/tiles/tile-old-money.avif", "/images/categories/men.avif"],
      },
      {
        color: "Dark Chocolate",
        colorHex: "#3D2314",
        size: "32",
        sku: "DF-MN-01-CH-32",
        stock: 14,
        images: ["/images/categories/men.avif", "/images/tiles/tile-old-money.avif"],
      },
    ],
  },
  {
    id: "df-ow-01",
    title: "Unstructured Summer Linen-Cotton Blazer",
    slug: "unstructured-summer-linen-cotton-blazer",
    category: "outerwear",
    brand: "Dream Fashion Tailoring",
    description: "An effortless unlined blazer constructed from breathable Italian linen blend. Notch lapel, patch pockets, and soft shoulder design for relaxed elegance.",
    shortDescription: "Lightweight unstructured summer blazer in linen-cotton blend.",
    fabricAndCare: "55% Linen, 45% Cotton. Dry clean only.",
    basePrice: 4850,
    salePrice: 3950,
    isNew: true,
    isTrending: false,
    isFeatured: true,
    tags: ["outerwear", "blazer", "men", "summer", "premium"],
    rating: 5.0,
    reviewCount: 15,
    variants: [
      {
        color: "Oatmeal Beige",
        colorHex: "#E3DAC9",
        size: "38",
        sku: "DF-OW-01-BG-38",
        stock: 8,
        images: ["/images/categories/outerwear.avif", "/images/tiles/tile-old-money.avif"],
      },
      {
        color: "Oatmeal Beige",
        colorHex: "#E3DAC9",
        size: "40",
        sku: "DF-OW-01-BG-40",
        stock: 12,
        images: ["/images/categories/outerwear.avif", "/images/tiles/tile-old-money.avif"],
      },
      {
        color: "Oatmeal Beige",
        colorHex: "#E3DAC9",
        size: "42",
        sku: "DF-OW-01-BG-42",
        stock: 10,
        images: ["/images/categories/outerwear.avif", "/images/tiles/tile-old-money.avif"],
      },
    ],
  },
  {
    id: "df-dr-01",
    title: "Bias-Cut Silk Satin Midi Silhouette Dress",
    slug: "bias-cut-silk-satin-midi-silhouette-dress",
    category: "dresses",
    brand: "Dream Fashion Atelier",
    description: "Flowing bias-cut midi dress cut from heavy silk-touch satin. Flattering diagonal drape, delicate cowl neckline, and adjustable shoulder straps.",
    shortDescription: "Heavy silk-touch satin bias-cut midi dress with cowl neck.",
    fabricAndCare: "100% Premium Satin. Hand wash cold or dry clean.",
    basePrice: 3250,
    salePrice: 2650,
    isNew: true,
    isTrending: true,
    isFeatured: true,
    tags: ["dresses", "women", "satin", "trending", "evening"],
    rating: 4.9,
    reviewCount: 22,
    variants: [
      {
        color: "Champagne Gold",
        colorHex: "#F7E7CE",
        size: "S",
        sku: "DF-DR-01-GD-S",
        stock: 10,
        images: ["/images/lookbook/look-3.avif", "/images/categories/dresses.avif"],
      },
      {
        color: "Champagne Gold",
        colorHex: "#F7E7CE",
        size: "M",
        sku: "DF-DR-01-GD-M",
        stock: 15,
        images: ["/images/lookbook/look-3.avif", "/images/categories/dresses.avif"],
      },
      {
        color: "Champagne Gold",
        colorHex: "#F7E7CE",
        size: "L",
        sku: "DF-DR-01-GD-L",
        stock: 12,
        images: ["/images/lookbook/look-3.avif", "/images/categories/dresses.avif"],
      },
    ],
  },
  {
    id: "df-wm-01",
    title: "Tailored Relaxed Fit Viscose Shirt",
    slug: "tailored-relaxed-fit-viscose-shirt",
    category: "women",
    brand: "Dream Fashion Atelier",
    description: "Modern oversized relaxed shirt tailored from fluid crepe viscose. Clean concealed placket, dropped shoulders, and wide cuffs.",
    shortDescription: "Fluid crepe viscose oversized tailored shirt for women.",
    fabricAndCare: "100% Viscose Crepe. Hand wash cold.",
    basePrice: 2150,
    salePrice: 1750,
    isNew: false,
    isTrending: true,
    isFeatured: true,
    tags: ["women", "shirt", "casual", "trending"],
    rating: 4.8,
    reviewCount: 16,
    variants: [
      {
        color: "Ivory White",
        colorHex: "#FFFFF0",
        size: "S",
        sku: "DF-WM-01-IV-S",
        stock: 14,
        images: ["/images/categories/women.avif", "/images/lookbook/look-3.avif"],
      },
      {
        color: "Ivory White",
        colorHex: "#FFFFF0",
        size: "M",
        sku: "DF-WM-01-IV-M",
        stock: 18,
        images: ["/images/categories/women.avif", "/images/lookbook/look-3.avif"],
      },
    ],
  },
];


export const INITIAL_LOGISTICS_SETTINGS: LogisticsSettings = {
  mode: "global",
  globalInsideDhaka: 150,
  globalOutsideDhaka: 150,
  paymentMethods: {
    cod: true,
    partial: true,
    full: true,
  },
  partialAdvanceType: "fixed",
  partialAdvanceValue: 150,
  insideDhakaDeliveryTime: "1-2 days",
  outsideDhakaDeliveryTime: "2-4 days",
  deliveryNote: "Dhaka 1-2 days (৳150) · Outside 2-4 days (৳150)",
  codNote: "Cash on Delivery (COD) available",
  exchangeGuaranteeNote: "Hassle-free 7-day size exchange guarantee",
};

export const INITIAL_DELIVERY_ZONES: DeliveryZone[] = [
  {
    id: "dhaka-city",
    type: "district",
    divisionId: "6",
    districtId: "47",
    charge: 60,
    estimatedDays: "1-2 days",
  },
  {
    id: "chattogram-metro",
    type: "district",
    divisionId: "1",
    districtId: "8",
    charge: 100,
    estimatedDays: "2-3 days",
  }
];

export const INITIAL_COUPONS: Coupon[] = [
  {
    id: "dream10",
    code: "DREAM10",
    type: "percent",
    value: 10,
    minOrder: 1000,
    expiresAt: "2026-12-31T23:59:59.000Z",
    usageLimit: 1000,
    usedCount: 14,
    active: true,
  },
  {
    id: "dream200",
    code: "DREAM200",
    type: "fixed",
    value: 200,
    minOrder: 2000,
    expiresAt: "2026-12-31T23:59:59.000Z",
    usageLimit: 500,
    usedCount: 22,
    active: true,
  },
  {
    id: "dream15",
    code: "DREAM15",
    type: "percent",
    value: 15,
    minOrder: 1500,
    expiresAt: "2026-12-31T23:59:59.000Z",
    usageLimit: 500,
    usedCount: 8,
    active: true,
  },
  {
    id: "freeship",
    code: "FREESHIP",
    type: "fixed",
    value: 120,
    minOrder: 1200,
    expiresAt: "2026-12-31T23:59:59.000Z",
    usageLimit: 500,
    usedCount: 5,
    active: true,
  },
];

export const INITIAL_HOME_SECTIONS: HomeSection[] = [
  {
    id: "sec-hero",
    type: "hero_carousel",
    title: "Hero Banner Slider",
    active: true,
    order: 1,
  },
  {
    id: "sec-trending-strip",
    type: "trending_strip",
    title: "Trending Visual Strip",
    active: true,
    order: 2,
  },
  {
    id: "sec-featured-grid",
    type: "product_grid",
    title: "Featured Products",
    subtitle: "Curated styles for the season",
    filterType: "all",
    viewAllLink: "/shop",
    limit: 8,
    active: true,
    order: 3,
  },
  {
    id: "sec-new-arrivals",
    type: "product_rail",
    title: "New Arrivals",
    subtitle: "Explore the latest casual shirts and polos",
    filterType: "new",
    viewAllLink: "/shop?sort=newest",
    limit: 8,
    active: true,
    order: 4,
  },
  {
    id: "sec-lookbook",
    type: "lookbook",
    title: "Editorial Lookbook",
    active: true,
    order: 5,
  },
  {
    id: "sec-promo",
    type: "promo_banner",
    title: "Flash Sale Promo Banner",
    bannerHeading: "SUMMER CLEARANCE UP TO 40% OFF",
    bannerSubtext: "Limited-edition tailoring, signature polos, and lightweight casual shirts.",
    bannerCtaText: "EXPLORE SALE",
    bannerCtaLink: "/shop?sale=true",
    bannerBgTheme: "dark",
    active: true,
    order: 6,
  },
  {
    id: "sec-trust",
    type: "trust_row",
    title: "Trust Badges & Guarantees",
    active: true,
    order: 7,
  },
];

export async function seedFirestoreDatabase(): Promise<{ success: boolean; message: string }> {
  try {
    const batch = writeBatch(db);

    batch.set(doc(db, "settings", "announcement"), INITIAL_ANNOUNCEMENT);
    batch.set(doc(db, "settings", "home_sections"), { sections: INITIAL_HOME_SECTIONS });
    for (const cat of INITIAL_CATEGORIES) {
      batch.set(doc(db, "categories", cat.id), cat);
    }
    for (const prod of INITIAL_PRODUCTS) {
      batch.set(doc(db, "products", prod.id), prod);
    }
    for (const ban of INITIAL_BANNERS) {
      batch.set(doc(db, "banners", ban.id), ban);
    }
    for (const zone of INITIAL_DELIVERY_ZONES) {
      batch.set(doc(db, "deliveryZones", zone.id), zone);
    }
    batch.set(doc(db, "settings", "logistics"), INITIAL_LOGISTICS_SETTINGS);
    for (const coupon of INITIAL_COUPONS) {
      batch.set(doc(db, "coupons", coupon.id), coupon);
    }

    await batch.commit();
    return { success: true, message: "Database updated with latest catalog & settings!" };
  } catch (error: any) {
    console.error("Firestore seeding error:", error);
    return { success: false, message: error.message || "Failed to seed database" };
  }
}
